#!/usr/bin/env ruby

require 'colorize'
require 'date'

d = DateTime.now

haec_annus = d.year
haec_mensis = d.month

haec_uno_dies = DateTime.new(haec_annus,haec_mensis,1).wday

["Su","Mo","Tu","We","Th","Fr","Sa"].each { |dow|
  printf dow+" "
}
puts

(1.. haec_uno_dies).each {
  printf "  "
}

(1..31).each { |dies|
  diesprop = DateTime.new(haec_annus,haec_mensis,dies)
  if diesprop.wday == 0
    puts
  end
  vdies = dies.to_s
  if (dies < 10)
    vdies = " "+vdies
  end
  if diesprop.day == d.day
    printf (vdies+" ").red
  else
    printf vdies+" "
  end
}

puts

